local dired = require("bits.dired.dired")

local M = {}
M.setup = function()
	vim.api.nvim_create_user_command("Dired", function(o)
		dired.open_dir(o.args)
	end, {
		nargs = "?",
		complete = "dir",
	})
	vim.api.nvim_create_user_command("DiredMark", function()
		dired.mark_file()
	end, {})
	vim.api.nvim_create_user_command("DiredMarkRange", function()
		dired.mark_file_range()
	end, {})
	vim.api.nvim_create_user_command("DiredGoBack", function()
		dired.go_back()
	end, {})
	vim.api.nvim_create_user_command("DiredGoUp", function()
		dired.go_up()
	end, {})
	vim.api.nvim_create_user_command("DiredEnter", function()
		dired.enter_dir()
	end, {})
	vim.api.nvim_create_user_command("DiredCreate", function()
		dired.create_file()
	end, {})
	vim.api.nvim_create_user_command("DiredDuplicate", function()
		dired.duplicate_file()
	end, {})
	vim.api.nvim_create_user_command("DiredRename", function()
		dired.rename_file()
	end, {})
	vim.api.nvim_create_user_command("DiredDelete", function()
		dired.delete_file()
	end, {})
	vim.api.nvim_create_user_command("DiredDeleteRange", function()
		dired.delete_file_range()
	end, {})
	vim.api.nvim_create_user_command("DiredDeleteMarked", function()
		dired.delete_marked()
	end, {})
	vim.api.nvim_create_user_command("DiredCopy", function()
		dired.clip_file("copy")
	end, {})
	vim.api.nvim_create_user_command("DiredCopyRange", function()
		dired.clip_file_range("copy")
	end, {})
	vim.api.nvim_create_user_command("DiredCopyMarked", function()
		dired.clip_marked("copy")
	end, {})
	vim.api.nvim_create_user_command("DiredMove", function()
		dired.clip_file("move")
	end, {})
	vim.api.nvim_create_user_command("DiredMoveRange", function()
		dired.clip_file_range("move")
	end, {})
	vim.api.nvim_create_user_command("DiredMoveMarked", function()
		dired.clip_marked("move")
	end, {})
	vim.api.nvim_create_user_command("DiredPaste", function()
		dired.paste_file()
	end, {})
	vim.api.nvim_create_user_command("DiredToggleHidden", function()
		dired.toggle_hidden_files()
	end, {})
	vim.api.nvim_create_user_command("DiredToggleSortOrder", function()
		dired.toggle_sort_order()
	end, {})
	vim.api.nvim_create_user_command("DiredToggleColors", function()
		dired.toggle_colors()
	end, {})
	vim.api.nvim_create_user_command("DiredToggleIcons", function()
		dired.toggle_show_icons()
	end, {})
	vim.api.nvim_create_user_command("DiredToggleHideDetails", function()
		dired.toggle_hide_details()
	end, {})
	vim.api.nvim_create_user_command("DiredQuit", function()
		dired.quit_buf()
	end, {})
	vim.api.nvim_create_user_command("DiredShellCmd", function()
		dired.shell_cmd()
	end, {})
	vim.api.nvim_create_user_command("DiredShellCmdCurrPath", function()
		dired.shell_cmd_curr_path()
	end, {})
	vim.api.nvim_create_user_command("DiredShellCmdMarked", function()
		dired.shell_cmd_marked()
	end, {})
end
return M
